### ISSUE TITLE
paginationの作成

### ISSUE THREAD

**Issue by mikana0918** [DJMasaru/training#2]
## 仕様
1ページごとに10件の投稿を表示する。
Laravelのviewにページネーションを表示して、ページごとの一覧を取得できるようにする。

参考：
https://laravel.com/docs/9.x/pagination#main-content
https://readouble.com/laravel/9.x/ja/pagination.html

**Comment by DJMasaru** [comment]
課題点を解決した。
レイアウトが崩れる原因はLaravelのページネーションがデフォルトでTailwind互換になっているからであった。
よってBootstrapページネーションのサポートを利用すべくAppServiceProviderに追記を行った。
マークアップについては今後、拡充していきたい。

<img width="568" alt="スクリーンショット 2022-12-08 0 00 11" src="https://user-images.githubusercontent.com/91363928/206213608-40bba5e8-cbfc-42e6-8c7a-e863d12ef2b3.png">
